### ISSUE TITLE
`branch_delete': undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by ChrisDoddGit** [tinglesoftware/dependabot-azure-devops#825]
**Describe the bug**
When running Dependabot after the update to 1.21.566 I get a failure for package react-select, likely related to abandoning feature / branch deletion as a PR for this package already exists.

2023-09-25T19:55:26.7371146Z Checking if react-select 2.0.0 needs updating
2023-09-25T19:55:27.0954513Z 🌍 --> GET https://registry.npmjs.org/react-select
2023-09-25T19:55:27.4052931Z 🌍 <-- 200 https://registry.npmjs.org/react-select
2023-09-25T19:55:27.4219088Z 🌍 --> GET https://registry.npmjs.org/react-select/5.7.5
2023-09-25T19:55:27.7300158Z 🌍 <-- 200 https://registry.npmjs.org/react-select/5.7.5
2023-09-25T19:55:41.1181925Z Requirements to unlock own
2023-09-25T19:55:41.1188579Z Requirements update strategy bump_versions
2023-09-25T19:55:41.1193454Z Updating react-select from 2.0.0 to 5.7.5
2023-09-25T19:55:54.4450263Z 🌍 --> GET https://dev.azure.com/**My org**/Website/_apis/git/repositories/meteor-portal/refs?filter=heads/dependabot/npm_and_yarn/develop/react-select-5.6.0
2023-09-25T19:55:54.7311049Z 🌍 <-- 200 https://dev.azure.com/**My org**/Website/_apis/git/repositories/meteor-portal/refs?filter=heads/dependabot/npm_and_yarn/develop/react-select-5.6.0
2023-09-25T19:55:54.7457106Z /home/dependabot/dependabot-updater/bin/azure_helpers.rb:35:in `branch_delete': undefined method `[]' for nil:NilClass (NoMethodError)
2023-09-25T19:55:54.7458447Z 
2023-09-25T19:55:54.7459540Z         branch_object_id = branch(branch_name)["objectId"]
2023-09-25T19:55:54.7460657Z                                               ^^^^^^^^^^^^
2023-09-25T19:55:54.7462648Z 	from bin/update_script.rb:782:in `block (2 levels) in <main>'
2023-09-25T19:55:54.7465025Z 	from bin/update_script.rb:749:in `each'
2023-09-25T19:55:54.7466559Z 	from bin/update_script.rb:749:in `block in <main>'
2023-09-25T19:55:54.7468063Z 	from bin/update_script.rb:565:in `each'
2023-09-25T19:55:54.7470005Z 	from bin/update_script.rb:565:in `<main>'
2023-09-25T19:55:55.2227509Z ##[error]The process '/usr/bin/docker' failed with exit code 1
2023-09-25T19:55:55.2269549Z ##[section]Finishing: Run Dependabot - portal

**Extension (please complete the following information):**
 - Host: Self hosted Azure pipeline
 - Version 1.21.566

**Server (please complete the following information):**
 - Region Western Canada

**Additional context**
All other repositories work fine, unlikely related to package. Likely the automatic deletion process.

**Comment by ChrisDoddGit** [comment]
Closed to save reviewer time as not a big issues and was easily solved by manually deleting branch
